### ISSUE TITLE
Flickering Integration test with hub

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1456]
The integration test with hub can fail with following error:
``` Web3-Torrent Integration Tests › allows peers to start torrenting

    TypeError: Cannot read property 'toHexString' of undefined

      at new v (http:/localhost:3000/static/js/0.chunk.js:34957:76)
      at Object.y [as bigNumberify] (http:/localhost:3000/static/js/0.chunk.js:34964:39)
      at convertToChannelState (http:/localhost:3000/static/js/main.chunk.js:4907:59)
      at PaymentChannelClient._callee5$ (http:/localhost:3000/static/js/main.chunk.js:4579:41)
      at tryCatch (http:/localhost:3000/static/js/0.chunk.js:187063:17)
      at Generator.invoke [as _invoke] (http:/localhost:3000/static/js/0.chunk.js:187282:22)
      at Generator.prototype.<computed> [as next] (http:/localhost:3000/static/js/0.chunk.js:187116:21)
      at asyncGeneratorStep (http:/localhost:3000/static/js/0.chunk.js:223:24)
      at _next (http:/localhost:3000/static/js/0.chunk.js:245:9)
      at Suite.Object.<anonymous>.describe (puppeteer/__tests__/web3torrent/seed-download.test.ts:59:3)
      at Object.<anonymous> (puppeteer/__tests__/web3torrent/seed-download.test.ts:25:1)
```

Example of the flickering here:
- first run (fail) https://app.circleci.com/pipelines/github/statechannels/monorepo/5106/workflows/7cbed1c0-51ac-4340-9e2e-80023490abfa/jobs/18754
- second run (pass) https://app.circleci.com/pipelines/github/statechannels/monorepo/5106/workflows/3f29c6c6-0d40-4f9c-b406-a7f24e13889f

**Comment by lalexgap** [comment]
Note: The integration test is failing on `master` right now due to another issue. Once that is resolved we should be able to investigate this.

**Comment by andrewgordstewart** [comment]
Based on the logs, I believe this is happening in [this code.](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/clients/payment-channel-client.ts#L204-L208)

**Comment by andrewgordstewart** [comment]
I rebased https://github.com/statechannels/monorepo/pull/1466 onto ags/separate-logs-per-e2e-test-file, and that produced [this failure](https://app.circleci.com/pipelines/github/statechannels/monorepo/5219/workflows/63ae0dbc-3bb5-4e16-8883-1c60980f9937/jobs/19360) (with a different error message).

When I ran the test locally, I witnessed the `TypeError: Cannot read property 'toHexString' of undefined` error on one test run.

**Comment by andrewgordstewart** [comment]
[This failure](https://app.circleci.com/pipelines/github/statechannels/monorepo/5227/workflows/33472b40-ff5a-469e-80c7-e4e9c0851bda/jobs/19406) threw the error in the issue description:
`TypeError: Cannot read property 'toHexString' of undefined`

The [browser logs](https://19406-209829093-gh.circle-artifacts.com/0/tmp/seed-download.browser.log) indicate there might be an issue with firebase-server, but given that the linked failure is the _direct_ funding integration test, that's probably a red herring.

I'm going to look through the [pino logs](https://19406-209829093-gh.circle-artifacts.com/0/tmp/seed-download.pino.log)

**Comment by andrewgordstewart** [comment]
In the pino logs, I found two state updates sent to the leecher with turn number 22:
```
[1587164655085] INFO  (xstate-wallet): OUTGOING JSONRPC REQUEST:
    jsonRpcResponse: {
      "jsonrpc": "2.0",
      "method": "ChannelUpdated",
      "params": {
        "participants": [
          {
            "participantId": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
            "signingAddress": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
            "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31"
          },
          {
            "participantId": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
            "signingAddress": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
            "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39"
          }
        ],
        "allocations": [
          {
            "allocationItems": [
              {
                "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31",
                "amount": "0x00000000000000000000000000000000000000000000000000000000000a5b00"
              },
              {
                "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39",
                "amount": "0x0000000000000000000000000000000000000000000000000000000000acc000"
              }
            ],
            "token": "0x0000000000000000000000000000000000000000"
          }
        ],
        "appDefinition": "0x430869383d611bBB1ce7Ca207024E7901bC26b40",
        "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "status": "closing",
        "turnNum": "0x0000000000000000000000000000000000000000000000000000000000000016",
        "channelId": "0x8b1404fb2f973a98549173f9d5d9a959765e2d7d8373ac03a41bb02c0e234497"
      }
    }
    browserId: 1

[1587164655087] INFO  (web3torrent): Channel updated to turnNum 22
    module: "web3torrent-lib"
    browserId: 1

[1587164655101] INFO  (xstate-wallet): OUTGOING JSONRPC REQUEST:
    jsonRpcResponse: {
      "jsonrpc": "2.0",
      "method": "ChannelUpdated",
      "params": {
        "participants": [
          {
            "participantId": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
            "signingAddress": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
            "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31"
          },
          {
            "participantId": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
            "signingAddress": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
            "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39"
          }
        ],
        "allocations": [
          {
            "allocationItems": [
              {
                "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31",
                "amount": "0x00000000000000000000000000000000000000000000000000000000000a5b00"
              },
              {
                "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39",
                "amount": "0x0000000000000000000000000000000000000000000000000000000000acc000"
              }
            ],
            "token": "0x0000000000000000000000000000000000000000"
          }
        ],
        "appDefinition": "0x430869383d611bBB1ce7Ca207024E7901bC26b40",
        "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "status": "running",
        "turnNum": "0x0000000000000000000000000000000000000000000000000000000000000016",
        "channelId": "0x8b1404fb2f973a98549173f9d5d9a959765e2d7d8373ac03a41bb02c0e234497"
      }
    }
    browserId: 1

[1587164655102] INFO  (web3torrent): Channel updated to turnNum 22
    module: "web3torrent-lib"
    browserId: 1
```

**Comment by lalexgap** [comment]
@andrewgordstewart nice catch!

**Comment by andrewgordstewart** [comment]
What might be happening above is:
1. the leecher is in the middle of making a payment
2. the leecher then asks to cancel the download, triggering `close-channel`
3. This results in two asynchronous calls to `store.signAndAddState`: call1, call2 with turn number 22
4. One of call1 or call2 gets the lock first
5. The second call overwrites the first

I don't see how this would cause an undefined error like in the flickering test, but it sure doesn't look good 👀

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/commit/285872e1db41cb6f2735892f816db9413a6c66ee <- this might resolve the `undefined` error

**Comment by andrewgordstewart** [comment]
I did the following
```
# https://app.circleci.com/pipelines/github/statechannels/monorepo/5227/workflows/33472b40-ff5a-469e-80c7-e4e9c0851bda/jobs/19406

cat seed-download.pino.log | jq -s -c 'sort_by(.time) | .[]' > sorted.log

# Sort lines by line length
cat sorted.log | jq -c 'delpaths([])' | awk '{ print length(), $0 | "sort -n" }' | tail -n 1 > longLine.json

# Recursively use this to strip most data
cat sorted.log | jq -c 'delpaths([["torrent"], ["pieces"], ["from"], ["wire", "_ext"]])' > stripTorrentData.log

du -sh *
# 4.0K    investigation.sh
# 260K    longLine.json
# 2.2M    seed-download.pino.log
# 2.2M    sorted.log
# 372K    stripTorrentData.log

cat stripTorrentData.log | tail -n 200 | yarn pino-pretty > tail.txt
```

When I look at the calls to `convertChannelResult`, I noticed [this one](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/clients/payment-channel-client.ts#L205-L206) was most likely to be the culprit, since the wallet was trying to close the channels.

When I looked in `tail.txt`, I found three log statements with the same JsonRpc ID:
```
[1587164655042] INFO  (xstate-wallet): INCOMING JSONRPC REQUEST:
    jsonRpcRequest: {
      "jsonrpc": "2.0",
      "method": "CloseChannel",
      "params": {
        "channelId": "0x8b1404fb2f973a98549173f9d5d9a959765e2d7d8373ac03a41bb02c0e234497"
      },
      "id": 1587164655041
    }
    browserId: 1

[1587164655049] INFO  (xstate-wallet): INCOMING JSONRPC REQUEST:
    jsonRpcRequest: {
      "jsonrpc": "2.0",
      "method": "PushMessage",
      "params": {
        "recipient": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
        "sender": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
        "data": {
          "signedStates": [
            {
              "challengeDuration": "0x000000000000000000000000000000000000000000000000000000000000012c",
              "channelNonce": "0x0000000000000000000000000000000000000000000000000000000000000000",
              "turnNum": "0x0000000000000000000000000000000000000000000000000000000000000016",
              "outcome": [
                {
                  "assetHolderAddress": "0x0116090EfeC8A6c176A094d3094c58811a7eA39c",
                  "allocationItems": [
                    {
                      "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31",
                      "amount": "0x00000000000000000000000000000000000000000000000000000000000a5b00"
                    },
                    {
                      "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39",
                      "amount": "0x0000000000000000000000000000000000000000000000000000000000acc000"
                    }
                  ]
                }
              ],
              "channelId": "0x8b1404fb2f973a98549173f9d5d9a959765e2d7d8373ac03a41bb02c0e234497",
              "signatures": [
                "0x16383e92a02c2334001ab63fe8e7a07cb3a96fcfdf615a196f1c530da1239f53262976d760a8b1d5359b6f84984d87b1127c4d7c69126583331bb7d4941fc0c41c"
              ],
              "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
              "appDefinition": "0x430869383d611bBB1ce7Ca207024E7901bC26b40",
              "isFinal": false,
              "chainId": "9001",
              "participants": [
                {
                  "participantId": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
                  "signingAddress": "0x9F1D075ee138758F8CB3823B40dc7027D6E1bE94",
                  "destination": "0x000000000000000000000000D9995BAE12FEe327256FFec1e3184d492bD94C31"
                },
                {
                  "participantId": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
                  "signingAddress": "0x65bf414aD7e3F5F9BB61201A45728730F9F0D9B5",
                  "destination": "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39"
                }
              ]
            }
          ]
        }
      },
      "id": 1587164655041
    }
    browserId: 1

[1587164655101] INFO  (xstate-wallet): OUTGOING JSONRPC REQUEST:
    jsonRpcResponse: {
      "id": 1587164655041,
      "jsonrpc": "2.0",
      "result": {
        "success": true
      }
    }
    browserId: 1
```

So, I believe what is happening is:
1. there are two JsonRpc calls with the _same_ id
  a. a `closeChannel` call
  b. a `pushMessage` call
2. The wallet processes (b) first, and sends back a response
3. the channel provider returns the response from (b) for the call in (a)
4. Now, web3torrent is calling `convertChannelResult` on the object `{success: true}`

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/blob/master/packages/channel-provider/src/messaging-service.ts#L57-L59

The channel provider does not guarantee uniqueness of request IDs!
