### ISSUE TITLE
[nitro-protocol] solc 0.6.6 docgen fails

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1550]
Attempted [here](https://app.circleci.com/pipelines/github/statechannels/monorepo/5474/workflows/7571d1a6-3227-42aa-82cb-0d711ba0525f/jobs/20732)
```
@statechannels/nitro-protocol: $ solidoc
@statechannels/nitro-protocol: [1587752633909] INFO  (684 on be24f60bbaeb): Create the directory for the output path: %s.
@statechannels/nitro-protocol: [1587752633911] INFO  (684 on be24f60bbaeb): Parsing /home/circleci/project/packages/nitro-protocol/build
@statechannels/nitro-protocol: [1587752633977] INFO  (684 on be24f60bbaeb): Total contracts: 27.
@statechannels/nitro-protocol: /home/circleci/project/node_modules/solidoc/helpers/documentation-helper.js:6
@statechannels/nitro-protocol:     const members = contents.split("@");
@statechannels/nitro-protocol:                              ^
@statechannels/nitro-protocol: TypeError: contents.split is not a function
@statechannels/nitro-protocol:     at Object.get (/home/circleci/project/node_modules/solidoc/helpers/documentation-helper.js:6:30)
@statechannels/nitro-protocol:     at Object.getNotice (/home/circleci/project/node_modules/solidoc/helpers/documentation-helper.js:19:24)
@statechannels/nitro-protocol:     at Object.serialize (/home/circleci/project/node_modules/solidoc/serializers/contract-serializer.js:92:40)
@statechannels/nitro-protocol:     at resolve (/home/circleci/project/node_modules/solidoc/generator.js:18:29)
@statechannels/nitro-protocol:     at /home/circleci/project/node_modules/require-all/index.js:56:38
@statechannels/nitro-protocol:     at Array.forEach (<anonymous>)
@statechannels/nitro-protocol:     at requireAll (/home/circleci/project/node_modules/require-all/index.js:34:9)
@statechannels/nitro-protocol:     at serializeContract (/home/circleci/project/node_modules/solidoc/generator.js:14:25)
@statechannels/nitro-protocol:     at Object.serialize (/home/circleci/project/node_modules/solidoc/generator.js:31:22)
@statechannels/nitro-protocol:     at begin (/home/circleci/project/node_modules/solidoc/cli.js:85:13)
```

**Comment by geoknee** [comment]
I believe this issue is fixed by https://github.com/statechannels/solidoc/commit/1cba9fb16e66caa1b91e2322b3b80456a5bd9f78
