### ISSUE TITLE
[web3torrent] client-seeding.test.ts failure

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1556]
Sometimes the following error happens:
```
@statechannels/web3torrent: FAIL src/library/client-seeding.test.ts (30.214s)
@statechannels/web3torrent:   ● Seeding and Leeching › should perform the extended handshake between seeder and leecher
@statechannels/web3torrent:     : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:
@statechannels/web3torrent:       66 |   });
@statechannels/web3torrent:       67 | 
@statechannels/web3torrent:     > 68 |   it('should perform the extended handshake between seeder and leecher', done => {
@statechannels/web3torrent:          |   ^
@statechannels/web3torrent:       69 |     seeder.seed(defaultFile as File, defaultSeedingOptions(), seededTorrent => {
@statechannels/web3torrent:       70 |       leecherA.add(seededTorrent.magnetURI, {store: MemoryChunkStore}, () => {
@statechannels/web3torrent:       71 |         expect(leecherA.torrents.length).toEqual(1);
@statechannels/web3torrent:       at new Spec (../../node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@statechannels/web3torrent:       at Suite.Object.<anonymous>.describe (src/library/client-seeding.test.ts:68:3)
@statechannels/web3torrent:       at Object.<anonymous> (src/library/client-seeding.test.ts:26:1)
```

Recently seen [during CI](https://app.circleci.com/pipelines/github/statechannels/monorepo/5500/workflows/ad742501-92ad-4956-9411-d7b5591f07bd/jobs/20911)

**Comment by kerzhner** [comment]
Perhaps a related failure:
```
@statechannels/web3torrent: FAIL src/library/client-seeding.test.ts (27.619s)
@statechannels/web3torrent:   ● Seeding and Leeching › should be able to unchoke and finish a download
@statechannels/web3torrent:     : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:
@statechannels/web3torrent:       94 |   }, 10000);
@statechannels/web3torrent:       95 | 
@statechannels/web3torrent:     > 96 |   it('should be able to unchoke and finish a download', async done => {
@statechannels/web3torrent:          |   ^
@statechannels/web3torrent:       97 |     seeder.seed(defaultFile as File, defaultSeedingOptions(), seededTorrent => {
@statechannels/web3torrent:       98 |       seeder.once(ClientEvents.PEER_STATUS_CHANGED, ({peerAccount}) => {
@statechannels/web3torrent:       99 |         seeder.once(ClientEvents.PEER_STATUS_CHANGED, ({torrentPeers}) => {
@statechannels/web3torrent:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@statechannels/web3torrent:       at Suite.Object.<anonymous>.describe (src/library/client-seeding.test.ts:96:3)
@statechannels/web3torrent:       at Object.<anonymous> (src/library/client-seeding.test.ts:26:1)
@statechannels/xstate-wallet: {"level":50,"time":1589322356806,"pid":977,"hostname":"329f3f87b5a5","name":"xstate-wallet","error":"Couldn't find the signing key for any participant in wallet.","store":{"budgets":[],"channels":[],"ledgers":[],"nonces":[],"objectives":[],"privateKeys":[{"key":"0xC7549030ba16f2ddE742e64FE2065f72d0f2fdC4","value":"0xc5171022db944271485510cd81ab10c98e6e747f87d30330757d7c2c22c2d52d"}]},"callback":"() => __awaiter(this, void 0, void 0, function* () {\n            const addresses = participants.map(x => x.signingAddress);\n            const privateKeys = yield this.backend.privateKeys();\n          ...}","msg":"Transaction error"}
 ```

**Comment by snario** [comment]
Has this happened recently @kerzhner ?

**Comment by kerzhner** [comment]
I have seen it happen this week. Haven't dug in yet.
