### ISSUE TITLE
[e2e-test] "Cannot read property 'privateKey' of undefined",

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1593]
https://app.circleci.com/pipelines/github/statechannels/monorepo/5632/workflows/2bf81b2d-1ba8-4a35-967e-f94def0f8f39/jobs/21736

```
 FAIL  puppeteer/__tests__/web3torrent/seed-download.test.ts (48.39s)
  ● Console

    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:34
      Opening browsers
    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:41
      Waiting on pages
    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:47
      Loading dapps
    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:65
      A uploads a file
    console.log puppeteer/helpers.ts:213
      Approving metamask
    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:68
      B starts downloading...
    console.log puppeteer/helpers.ts:213
      Approving metamask
    console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:71
      Waiting for open channels
    console.log puppeteer/helpers.ts:297
      Waiting for create channel button
    console.error puppeteer/helpers.ts:70
      frame.waitForSelector(div.application-workflow-prompt > div > button) failed on frame 

  ● Web3-Torrent Integration Tests › allows peers to start torrenting

    TimeoutError: waiting for selector "div.application-workflow-prompt > div > button" failed: timeout 30000ms exceeded

      66 | ): Promise<void> {
      67 |   try {
    > 68 |     await frame.waitForSelector(selector);
         |                 ^
      69 |   } catch (error) {
      70 |     console.error(
      71 |       'frame.waitForSelector(' + selector + ') failed on frame ' + (await frame.title())

      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:432:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:627:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:112:23)
      at waitForAndClickButton (puppeteer/helpers.ts:68:17)
      at puppeteer/helpers.ts:302:11
          at Array.map (<anonymous>)
      at Object.it (puppeteer/__tests__/web3torrent/seed-download.test.ts:72:35)
```

**Comment by andrewgordstewart** [comment]
```
[1588124521600] INFO  (simple-hub/556 on 4aa68112f871): Starting server
    context: "firebase"
[1588124521617] INFO  (simple-hub/556 on 4aa68112f871): Started
    context: "firebase"
[1588124521645] INFO  (simple-hub/556 on 4aa68112f871): Closing server: unhandledRejection
    context: "firebase"
    err: {
      "type": "TypeError",
      "message": "Cannot read property 'privateKey' of undefined",
      "stack":
          TypeError: Cannot read property 'privateKey' of undefined
              at /home/circleci/project/packages/devtools/src/ganache/index.ts:113:73
              at Generator.next (<anonymous>)
              at fulfilled (/home/circleci/project/packages/devtools/lib/src/ganache/index.js:5:58)
              at process._tickCallback (internal/process/next_tick.js:68:7)
    }
[1588124521662] INFO  (simple-hub/556 on 4aa68112f871): Closed
    context: "firebase"
[1588124521662] INFO  (simple-hub/556 on 4aa68112f871): Closing server: exit
    context: "firebase"
    err: 0
```

**Comment by andrewgordstewart** [comment]
Note that I was hitting an issue where `Number(deployerAccountIndex)` was `NaN`.
