### ISSUE TITLE
States not stored in sorted order.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1789]
**Describe the bug :bug:**
The `supported` method was returning the wrong state (turn number 5, not turn number 6). This is because the `stateVariables` array, which is supposed to be [reverse-sorted by turn number](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/store/channel-store-entry.ts#L268-L271), was not: it had turns `[5,6]` instead of turns `[6,5]`.

The `support` function [depends](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/store/channel-store-entry.ts#L132-L154) on this sorting order, making 

**To Reproduce**
https://app.circleci.com/pipelines/github/statechannels/monorepo/6271/workflows/17fb204d-120b-4c95-93c6-5135eee80111/jobs/25959/steps

```
@statechannels/xstate-wallet: FAIL src/integration-tests/closing.test.ts (6.814s)
@statechannels/xstate-wallet:   ● Console
@statechannels/xstate-wallet:     console.error ../../node_modules/xstate/lib/utils.js:574
@statechannels/xstate-wallet:       Missing onError handler for invocation 'signFinalState', error was 'Error: Supported state not final'. Stacktrace was 'Error: Supported state not final
@statechannels/xstate-wallet:           at /home/circleci/project/packages/xstate-wallet/src/workflows/conclude-channel.ts:15:33
@statechannels/xstate-wallet:           at Generator.next (<anonymous>)
@statechannels/xstate-wallet:           at fulfilled (/home/circleci/project/packages/xstate-wallet/src/workflows/conclude-channel.ts:5:58)'
```

1. Checkout https://github.com/statechannels/monorepo/pull/1788/commits/68599b45907be783415c949c35adf911f2bb1bf4
2. Set a breakpoint [here](https://github.com/statechannels/monorepo/blob/68599b45907be783415c949c35adf911f2bb1bf4/packages/xstate-wallet/src/store/channel-store-entry.ts#L134), conditional on something like `this.signedStates[1].turnNum.toNumber() === 6`

**Additional context**
In https://github.com/statechannels/monorepo/pull/1788, I resolved this issue by using the dexie backend. I believe that the `transaction` method by this backend prevented this issue.

**Comment by andrewgordstewart** [comment]
Re-opening, since the fix in #1808 does not explain this bug (and this bug seems serious enough to understand).
