### ISSUE TITLE
[web3torrent] Audit useEffect hooks

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#2090]
We some errors in our [tests on circle](https://app.circleci.com/pipelines/github/statechannels/monorepo/7198/workflows/2d22d1fb-e6ba-499d-89e6-33dfda671276/jobs/32910) like this: 

```
@statechannels/web3torrent:       Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
 
@statechannels/web3torrent:           in App
 ```

I have seen warnings like this in the browser console before, but not recently, so it might be an issue confined to our test suite. 

We should check that we are following recommended patterns around event un-subscriptions in our react components.

**Comment by geoknee** [comment]
We `useEffect` only 8 times in our codebase. AFAICT each time we register an event handler, we also return an appropriate unsubscription function.

**Comment by geoknee** [comment]
The errors we see in our react tests look like this
```
 PASS  src/App.test.tsx (8.305s)
  ✓ renders app without crashing (132ms)

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: An update to App inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in App

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: An update to App inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in App

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in App

```
and
```
 PASS  src/pages/file/File.test.tsx
  <File />
    ✓ should render an download button (702ms)

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: An update to File inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in File
        in Router (created by MemoryRouter)
        in MemoryRouter (created by WrapperComponent)
        in WrapperComponent

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: An update to File inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in File
        in Router (created by MemoryRouter)
        in MemoryRouter (created by WrapperComponent)
        in WrapperComponent

  console.warn ../../node_modules/react-dom/cjs/react-dom.development.js:12357
    Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    
    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: lifecycle(Component)

  console.warn ../../node_modules/react-dom/cjs/react-dom.development.js:12357
    Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: lifecycle(Component)

  console.error ../../node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLCanvasElementImpl.getContext (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
        at HTMLCanvasElement.getContext (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:41:47)
        at Object.render (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/node_modules/ethereum-blockies/blockies.js:88:19)
        at BlockiesIdenticon.draw (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/src/Blockie/index.js:23:14)
        at BlockiesIdenticon.componentDidMount (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/src/Blockie/index.js:20:10)
        at commitLifeCycles (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:22101:22)
        at commitLayoutEffects (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:25344:7)
        at HTMLUnknownElement.callCallback (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:336:14)
        at innerInvokeEventListeners (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27) undefined

  console.error ../../node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot set property 'fillStyle' of null]
        at reportException (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:385:16)
        at invokeGuardedCallback (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:440:31)
        at commitRootImpl (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:25082:9)
        at unstable_runWithPriority (/Users/georgeknee/statechannels/monorepo/node_modules/scheduler/cjs/scheduler.development.js:697:12) TypeError: Cannot set property 'fillStyle' of null
        at Object.render (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/node_modules/ethereum-blockies/blockies.js:89:15)
        at BlockiesIdenticon.draw (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/src/Blockie/index.js:23:14)
        at BlockiesIdenticon.componentDidMount (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/node_modules/rimble-ui/src/Blockie/index.js:20:10)
        at commitLifeCycles (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:22101:22)
        at commitLayoutEffects (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:25344:7)
        at HTMLUnknownElement.callCallback (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:336:14)
        at innerInvokeEventListeners (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
        at invokeEventListeners (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/Users/georgeknee/statechannels/monorepo/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:385:16)
        at invokeGuardedCallback (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:440:31)
        at commitRootImpl (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:25082:9)
        at unstable_runWithPriority (/Users/georgeknee/statechannels/monorepo/node_modules/scheduler/cjs/scheduler.development.js:697:12)
        at runWithPriority$2 (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
        at commitRoot (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:24922:3)
        at finishSyncRender (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:24329:3)
        at performSyncWorkOnRoot (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:24307:9)
        at /Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:12199:24
        at unstable_runWithPriority (/Users/georgeknee/statechannels/monorepo/node_modules/scheduler/cjs/scheduler.development.js:697:12)
        at runWithPriority$2 (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
        at flushSyncCallbackQueueImpl (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:12194:7)
        at flushSyncCallbackQueue (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:12182:3)
        at scheduleUpdateOnFiber (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:23709:9)
        at dispatchAction (/Users/georgeknee/statechannels/monorepo/node_modules/react-dom/cjs/react-dom.development.js:17076:5)
        at Object.<anonymous> (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/src/hooks/use-budget.ts:15:7)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/georgeknee/statechannels/monorepo/packages/web3torrent/src/hooks/use-budget.ts:5:58)

  console.error ../../node_modules/react-dom/cjs/react-dom.development.js:21843
    The above error occurred in the <BlockiesIdenticon> component:
        in BlockiesIdenticon
        in div (created by ForwardRef(Avatar))
        in ForwardRef(Avatar) (created by WithStyles(ForwardRef(Avatar)))
        in WithStyles(ForwardRef(Avatar))
        in span (created by ForwardRef(Badge))
        in ForwardRef(Badge) (created by WithStyles(ForwardRef(Badge)))
        in WithStyles(ForwardRef(Badge))
        in Unknown (created by lifecycle(Component))
        in lifecycle(Component) (created by withHandlers(lifecycle(Component)))
        in withHandlers(lifecycle(Component)) (created by withStateHandlers(withHandlers(lifecycle(Component))))
        in withStateHandlers(withHandlers(lifecycle(Component))) (created by withStateHandlers(withStateHandlers(withHandlers(lifecycle(Component)))))
        in withStateHandlers(withStateHandlers(withHandlers(lifecycle(Component)))) (created by Popper)
        in Popper (created by Tooltip)
        in Tooltip
        in div
        in div
        in Unknown (created by File)
        in section (created by File)
        in File
        in Router (created by MemoryRouter)
        in MemoryRouter (created by WrapperComponent)
        in WrapperComponent
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by geoknee** [comment]
- Some of these errors appear to be caused by the Rimble <BlockieIdenticon> component. Fixing it may require adding support for `canvas` in our jest config. 
- Some of the errors complain about us not wrapping stuff in an `act` block as per guidelines https://reactjs.org/docs/test-utils.html#act. I tried to add this in but I still saw the error.
