### ISSUE TITLE
[wallet] direct funding transaction fails

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#587]
Using pupeeter I've managed to get two wallets to the point of direct funding. However when the direct funding transaction is submitted it fails.

```
ALERT: [ethjs-rpc] rpc error with payload {"id":9670155763436,"jsonrpc":"2.0","params":["0xf8cb108477359400832dc6c09470362dc2a6fc72c695eab15a0031951f770d123980b864278f2ab8ebd394ecceb43fbb4dc0a16b8fdaa88bce9a8485cce501c506b42f30c02da91a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001824676a0dcc64fb411ae9140eb9696bf2d38dba97893198ffc90966a27d757eb1e18ef49a026126a66357a256e478729340081717c11e2a2d74d1f436ddce3814bb89c122e"],"method":"eth_sendRawTransaction"} Error: VM Exception while processing transaction: revert
```

**Comment by lalexgap** [comment]
Error in ganache: 
```
eth_sendTransaction
   > {
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "gas": "0x2dc6c0",
   >       "to": "0x70362dc2A6fC72c695EAb15A0031951F770d1239",
   >       "data": "0x278f2ab8685e90609119058be7ede34b796df967f646723480472c700d8559a6b35ff00700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
   >       "from": "0xd9995bae12fee327256ffec1e3184d492bd94c31"
   >     }
   >   ],
   >   "id": 98,
   >   "jsonrpc": "2.0"
   > }

 <   {
 <     "id": 98,
 <     "jsonrpc": "2.0",
 <     "result": "0xe27de07663b86c1bc765d8920b25df17f75195f5fc35117cb84b46960e50a1e3",
 <     "error": {
 <       "message": "VM Exception while processing transaction: revert",
 <       "code": -32000,
 <       "data": {
 <         "0xe27de07663b86c1bc765d8920b25df17f75195f5fc35117cb84b46960e50a1e3": {
 <           "error": "revert",
 <           "program_counter": 152,
 <           "return": "0x"
 <         },
 <         "stack": "o: VM Exception while processing transaction: revert\n    at Function.o.fromResults (/Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:89727)\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:121953\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98498\n    at p (/Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98156)\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:98209\n    at t.default (/Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:544097)\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:99122\n    at t.n.emit (/Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:16355)\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:654328\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:654351\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:1093446\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:19209\n    at i (/Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:34308)\n    at /Users/alexgap/code/monorepo/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:14717\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
 <         "name": "o"
 <       }
 <     }
 <   }


  Transaction: 0xe27de07663b86c1bc765d8920b25df17f75195f5fc35117cb84b46960e50a1e3

  Gas usage: 23961
  Block Number: 31
  Block Time: Thu Nov 28 2019 16:21:59 GMT-0800 (Pacific Standard Time)
  Runtime Error: revert

```

**Comment by lalexgap** [comment]
This is due to the transaction being sent to the adjudicator instead of the asset holder.
