### ISSUE TITLE
[ganache] Starting RPS and Wallet at the same time fails

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#725]
When running `yarn start` in both `rps` and the `wallet` at roughly the same time contract deployment can fail in either `rps` or the `wallet`. It looks like the transaction nonce gets out of sync since there are transactions coming in that one deployer doesn't know about.

```
Compilation finished successfully

Found shared ganache instance running on http://localhost:8547.
Deployments will be written to /Users/alexgap/code/monorepo/ganache-deployments.json.
/Users/alexgap/code/monorepo/packages/rps/scripts/start.js:19
  throw err;
  ^

Error: the tx doesn't have the correct nonce. account has nonce of: 4 tx has nonce of: 3
    at getResult (/Users/alexgap/code/monorepo/node_modules/etherlime-lib/node_modules/ethers/providers/json-rpc-provider.js:40:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/alexgap/code/monorepo/node_modules/etherlime-lib/node_modules/ethers/utils/web.js:111:30)
    at exports.XMLHttpRequest.dispatchEvent (/Users/alexgap/code/monorepo/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/alexgap/code/monorepo/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/alexgap/code/monorepo/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
```

**Comment by lalexgap** [comment]
This isn't a  blocker since if `yarn start` fails you can just run it again and it will succeed.
